/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-05-13 10:28:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>RegisterForm</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//JavaScript Start code\r\n");
      out.write("function validate()//function\r\n");
      out.write("{\r\n");
      out.write("    \r\n");
      out.write("    var empname = document.getElementById(\"empname\").value;\r\n");
      out.write("    var email = document.getElementById(\"email\").value;\r\n");
      out.write("    var pass = document.getElementById(\"pass\").value;\r\n");
      out.write("    var age = document.getElementById(\"age\").value;\r\n");
      out.write("    var mobile = document.getElementById(\"mobile\").value;\r\n");
      out.write("   \r\n");
      out.write("    if(empname===\"\")//condition -1\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div2\").innerHTML=\"Enter a employee name\";\r\n");
      out.write("        document.getElementById(\"div2\").style.color=\"Red\";\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    else\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div2\").innerHTML=\"\";\r\n");
      out.write("    }\r\n");
      out.write("    if(email.indexOf(\"@\")> -1)//condition -2\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div4\").innerHTML=\"\";\r\n");
      out.write("    }\r\n");
      out.write("     else\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div4\").innerHTML=\"Enter the correct email address\";\r\n");
      out.write("        document.getElementById(\"div4\").style.color=\"Red\";\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    if(pass.length<=6)//condition -3\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div3\").innerHTML=\"Password is weak\";\r\n");
      out.write("        document.getElementById(\"div3\").style.color=\"Red\";\r\n");
      out.write("    }\r\n");
      out.write("     else\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div3\").innerHTML=\"\";\r\n");
      out.write("    }\r\n");
      out.write("    if(age===\"\")//condition -4\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div5\").innerHTML=\"Enter a age\";\r\n");
      out.write("        document.getElementById(\"div5\").style.color=\"Red\";\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    else\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div5\").innerHTML=\"\";\r\n");
      out.write("    }  \r\n");
      out.write("    if(mobile===\"\")//condition -6\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div6\").innerHTML=\"Give Phone Number\";\r\n");
      out.write("        document.getElementById(\"div6\").style.color=\"Red\";\r\n");
      out.write("    }\r\n");
      out.write("     else\r\n");
      out.write("    {\r\n");
      out.write("        document.getElementById(\"div6\").innerHTML=\"\";\r\n");
      out.write("    }\r\n");
      out.write("}    \r\n");
      out.write("//JavaScript end Code\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h3>NewRegisterForm</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("<!-- code start -->\r\n");
      out.write("<form action=\"registerformaction\" method=\"get\"><!-- Form action given -->\r\n");
      out.write("<table>\r\n");
      out.write("<!-- Table Design start -->\r\n");
      out.write("<tr><td>EmployeeName:</td><td><input type=\"text\" name=\"empname\" id=\"empname\" onClick=\"validate()\" requried/></td><td><h6 id=\"div2\"></h6></td></tr>\r\n");
      out.write("<tr><td>Email:</td><td><input type=\"text\" name=\"email\" id=\"email\" onClick=\"validate()\"/></td><td><h6 id=\"div4\"></h6></td></tr>\r\n");
      out.write("<tr><td>Password:</td><td><input type=\"password\" name=\"pass\" id=\"pass\" onClick=\"validate()\"/></td><td><h6 id=\"div3\"></h6></td></tr>\r\n");
      out.write("<tr><td>Age:</td><td><input type=\"text\" name=\"age\" id=\"age\" onClick=\"validate()\"/></td><td><h6 id=\"div5\"></h6></td></tr>\r\n");
      out.write("<tr><td>Dob:</td><td><input type=\"text\" name=\"dob\" placeholder=\"dd/mm/yyyy\" required/></td></tr>\r\n");
      out.write("<tr><td>Mobile:</td><td><input type=\"text\" name=\"mobile\" id=\"mobile\" onClick=\"validate()\" /></td><td><h6 id=\"div6\"></h6></td></tr>\r\n");
      out.write("<!-- <tr><td>Address:</td><td><input type=\"text\" name=\"addr\"/></td></tr> -->\r\n");
      out.write("<tr><td>Gender:</td><td><input type=\"radio\" name=\"gen\" value=\"male\"/>Male\r\n");
      out.write("<input type=\"radio\" name=\"gen\" value=\"female\"/>Female\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>Qualification:</td><td>\r\n");
      out.write("<select name=\"quali\">\r\n");
      out.write("<option>BE</option>\r\n");
      out.write("<option>BTECH</option>\r\n");
      out.write("<option>BSC</option>\r\n");
      out.write("<option>MSC</option>\r\n");
      out.write("</select>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><input type=\"submit\" value=\"Register\" onClick=\"validate()\"/></td></tr>\r\n");
      out.write("<!-- Table Design End -->\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<!-- Code End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
