/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-05-09 21:18:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>RegisterForm</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h3>NewRegisterForm</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("<form action=\"registerformaction\" method=\"get\">\r\n");
      out.write("<table>\r\n");
      out.write("<tr><td>RegId:</td><td><input type=\"text\" name=\"regid\" required/></td></tr>\r\n");
      out.write("<tr><td>RegName</td><td><input type=\"text\" name=\"regname\"/></td></tr>\r\n");
      out.write("<tr><td>Email:</td><td><input type=\"text\" name=\"email\" pattern=\"[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,3}$\"/></td></tr>\r\n");
      out.write("<tr><td>Password:</td><td><input type=\"pass\" name=\"pass\" pattern=\".{6,}\" title=\"Six or more characters\"/></td></tr>\r\n");
      out.write("<tr><td>Age:</td><td><input type=\"text\" name=\"age\"/></td></tr>\r\n");
      out.write("<tr><td>Dob:</td><td><input type=\"text\" name=\"dob\"/></td></tr>\r\n");
      out.write("<tr><td>Mobile:</td><td><input type=\"text\" name=\"mobile\"/></td></tr>\r\n");
      out.write("<tr><td>Address:</td><td><input type=\"text\" name=\"addr\"/></td></tr>\r\n");
      out.write("<tr><td>Gender:</td><td><input type=\"radio\" name=\"gen\" value=\"male\"/>Male\r\n");
      out.write("<input type=\"radio\" name=\"gen\" value=\"female\"/>Female\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>Role:</td><td><select name=\"role\">\r\n");
      out.write("<option>Trainer</option>\r\n");
      out.write("<option>Mentor</option>\r\n");
      out.write("<option>Manager</option>\r\n");
      out.write("</select></td></tr>\r\n");
      out.write("<tr><td>SkillSet:</td><td>Skill-1:<input type=\"checkbox\" name=\"java\" value=\"java\"/>Java\r\n");
      out.write("<br>\r\n");
      out.write("Skill-2:<input type=\"checkbox\" name=\"oops\" value=\"oops\"/>OOPS\r\n");
      out.write("<br>\r\n");
      out.write("Skill-3:<input type=\"checkbox\" name=\"devops\" value=\"devops\"/>Devops\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>Status:</td><td>\r\n");
      out.write("<select name=\"status\">\r\n");
      out.write("<option>NewStaff</option>\r\n");
      out.write("<option>OldStaff</option>\r\n");
      out.write("</select>\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td><input type=\"submit\" value=\"Register\"/></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
