/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-05-13 01:39:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class skillsetrequest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h3>SkillMaster</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("<h4><a href=\"ViewMyStatus.jsp\">ViewMyStatus</a></h4>\r\n");

HttpSession sess=request.getSession(true);
String s=(String)sess.getAttribute("email");




      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"skillsetrequestform\" method=\"get\">\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<tr><td>EmployeeEmail:</td><td><input type=\"text\" name=\"email\" value=\"");
      out.print(s);
      out.write("\"/></td></tr>\r\n");
      out.write("<tr><td>EmployeeName:</td><td><input type=\"text\" name=\"empname\"/></td></tr>\r\n");
      out.write("<tr><td>Qualification:</td><td><input type=\"text\" name=\"quali\"/></td></tr>\r\n");
      out.write("<tr><td>NoOfBatchs:</td><td><input type=\"text\" name=\"nobatch\"/></td></tr>\r\n");
      out.write("<tr><td>StudentsHandle:</td><td><input type=\"text\" name=\"stuh\"/></td></tr>\r\n");
      out.write("<tr><td>CurrentRole:</td><td><select name=\"crole\">\r\n");
      out.write("<option>Trainer</option>\r\n");
      out.write("<option>Mentor</option>\r\n");
      out.write("<option>Manager</option>\r\n");
      out.write("</select></td></tr>\r\n");
      out.write("<tr><td>RoleRequest:</td><td><select name=\"role\">\r\n");
      out.write("<option>SeniorTrainer</option>\r\n");
      out.write("<option>SeniorMentor</option>\r\n");
      out.write("<option>SeniorManager</option>\r\n");
      out.write("</select></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td>StudentsPlaced:</td><td><input type=\"text\" name=\"stup\"/></td></tr>\r\n");
      out.write("<tr><td></td><td><input type=\"hidden\" name=\"stus\" value=\"waiting\"/></td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td><input type=\"submit\" value=\"ADD\"/></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<h3>SkillSet</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("<form action=\"skillsetform\" method=\"get\">\r\n");
      out.write("<table>\r\n");
      out.write("<tr>\r\n");
      out.write("      <td><label>Certification:</label>&nbsp;</td>\r\n");
      out.write("      <td><select name=\"select2\" size=\"3\" multiple=\"multiple\" tabindex=\"1\">\r\n");
      out.write("        <option value=\"OracleSE6\">OracleSE6</option>\r\n");
      out.write("        <option value=\"OracleSE7\">OracleSE7</option>\r\n");
      out.write("        <option value=\"OracleSE8\">OracleSE8</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("<tr>\r\n");
      out.write("      <td><label>Skills:</label>&nbsp;</td>\r\n");
      out.write("      <td><select name=\"select3\" size=\"3\" multiple=\"multiple\" tabindex=\"1\">\r\n");
      out.write("        <option value=\"java\">Java</option>\r\n");
      out.write("        <option value=\"j2ee\">J2ee</option>\r\n");
      out.write("        <option value=\"devops\">devops</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr><td>EmployeeEmail:</td><td><input type=\"text\" name=\"email\" value=\"");
      out.print(s);
      out.write("\"/></td></tr>\r\n");
      out.write("        <tr><td><input type=\"submit\" value=\"ADDSKILLS\"/></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
