/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-04-01 10:16:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Tutorials-JHCPROGRAMMING</title>\r\n");
      out.write(" \r\n");
      out.write("       <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Material Design Bootstrap -->\r\n");
      out.write("    <link href=\"css/mdb.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Your custom styles (optional) -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("      <!--Footer-->\r\n");
      out.write("      <footer class=\"page-footer font-small stylish-color-dark pt-4 mt-4\">\r\n");
      out.write("      \r\n");
      out.write("          <!--Footer Links-->\r\n");
      out.write("          <div class=\"container text-center text-md-left\">\r\n");
      out.write("      \r\n");
      out.write("              <!-- Footer links -->\r\n");
      out.write("              <div class=\"row text-center text-md-left mt-3 pb-3\">\r\n");
      out.write("      \r\n");
      out.write("                  <!--First column-->\r\n");
      out.write("                  <div class=\"col-md-3 col-lg-3 col-xl-3 mx-auto mt-3\">\r\n");
      out.write("                      <h6 class=\"text-uppercase mb-4 font-weight-bold\">JHCPROGRAMMING</h6>\r\n");
      out.write("                      <p>Easy to learn Programs@Anytime@Anywhere</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--/.First column-->\r\n");
      out.write("      \r\n");
      out.write("                  <hr class=\"w-100 clearfix d-md-none\">\r\n");
      out.write("      \r\n");
      out.write("                  <!--Second column-->\r\n");
      out.write("                  <div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mt-3\">\r\n");
      out.write("                      <h6 class=\"text-uppercase mb-4 font-weight-bold\">Objective</h6>\r\n");
      out.write("                      <p><a href=\"#!\">Java</a></p>\r\n");
      out.write("                      <p><a href=\"#!\">C-Programming</a></p>\r\n");
      out.write("                      <p><a href=\"#!\">OOPS-Programming</a></p>\r\n");
      out.write("                      <p><a href=\"#!\">Bootstrap</a></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--/.Second column-->\r\n");
      out.write("      \r\n");
      out.write("                  <hr class=\"w-100 clearfix d-md-none\">\r\n");
      out.write("      \r\n");
      out.write("                  <!--Third column-->\r\n");
      out.write("                  <div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mt-3\">\r\n");
      out.write("                      <h6 class=\"text-uppercase mb-4 font-weight-bold\">Useful links</h6>\r\n");
      out.write("                      <p><a href=\"https://www.youtube.com/channel/UCARc3v6818KY-BfmOc2efUQ?view_as=subscriber\">@SubscribeYoutube</a></p>\r\n");
      out.write("                      <p><a href=\"https://www.youtube.com/playlist?list=PLExUa3EURkZVniQIyUuok-svoBpRFquAo\">CProgramming</a></p>\r\n");
      out.write("                      <p><a href=\"https://www.youtube.com/playlist?list=PLExUa3EURkZU9xGKbGSrJQSAZ8XE0V1cZ\">C++Programming</a></p>\r\n");
      out.write("                      <p><a href=\"https://www.youtube.com/playlist?list=PLExUa3EURkZU9xGKbGSrJQSAZ8XE0V1cZ\">JavaProgramming</a></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--/.Third column-->\r\n");
      out.write("      \r\n");
      out.write("                  <hr class=\"w-100 clearfix d-md-none\">\r\n");
      out.write("      \r\n");
      out.write("                  <!--Fourth column-->\r\n");
      out.write("                  <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mt-3\">\r\n");
      out.write("                      <h6 class=\"text-uppercase mb-4 font-weight-bold\">Contact</h6>\r\n");
      out.write("                      <p><i class=\"fa fa-home mr-3\"></i> Karur</p>\r\n");
      out.write("                      <p><i class=\"fa fa-envelope mr-3\"></i>jhcprogramming@gmail.com</p>\r\n");
      out.write("                      <p><i class=\"fa fa-phone mr-3\"></i>+919843095933</p>\r\n");
      out.write("<!--                       <p><i class=\"fa fa-print mr-3\"></i></p> -->\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--/.Fourth column-->\r\n");
      out.write("      \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- Footer links -->\r\n");
      out.write("      \r\n");
      out.write("              <hr>\r\n");
      out.write("      \r\n");
      out.write("              <div class=\"row py-3 d-flex align-items-center\">\r\n");
      out.write("      \r\n");
      out.write("                  <!--Grid column-->\r\n");
      out.write("                  <div class=\"col-md-8 col-lg-8\">\r\n");
      out.write("      \r\n");
      out.write("                      <!--Copyright-->\r\n");
      out.write("                      <p class=\"text-center text-md-left grey-text\">© 2018 Copyright: <a href=\"#!\"><strong> JHCPROGRAMMING</strong></a></p>\r\n");
      out.write("                      <!--/.Copyright-->\r\n");
      out.write("      \r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--Grid column-->\r\n");
      out.write("      \r\n");
      out.write("                  <!--Grid column-->\r\n");
      out.write("                  <div class=\"col-md-4 col-lg-4 ml-lg-0\">\r\n");
      out.write("      \r\n");
      out.write("                      <!--Social buttons-->\r\n");
      out.write("                      <div class=\"text-center text-md-right\">\r\n");
      out.write("                          <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("                              <li class=\"list-inline-item\"><a href=\"\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("                              <li class=\"list-inline-item\"><a  href=\"\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("                              <li class=\"list-inline-item\"><a  href=\"\"><i class=\"fa fa-google-plus\"></i></a></li>\r\n");
      out.write("                              <li class=\"list-inline-item\"><a  href=\"\"><i class=\"fa fa-linkedin\"></i></a></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <!--/.Social buttons-->\r\n");
      out.write("      \r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!--Grid column-->\r\n");
      out.write("      \r\n");
      out.write("              </div>\r\n");
      out.write("      \r\n");
      out.write("          </div>\r\n");
      out.write("      \r\n");
      out.write("      </footer>\r\n");
      out.write("      <!--/.Footer-->\r\n");
      out.write("                      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
