/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-04-01 10:17:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Tutorials-JHCPROGRAMMING</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"fb-root\"></div>\r\n");
      out.write("<script>(function(d, s, id) {\r\n");
      out.write("  var js, fjs = d.getElementsByTagName(s)[0];\r\n");
      out.write("  if (d.getElementById(id)) return;\r\n");
      out.write("  js = d.createElement(s); js.id = id;\r\n");
      out.write("  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.12';\r\n");
      out.write("  fjs.parentNode.insertBefore(js, fjs);\r\n");
      out.write("}(document, 'script', 'facebook-jssdk'));</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<!--Card group-->\r\n");
      out.write("<div class=\"card-deck\">\r\n");
      out.write("\r\n");
      out.write("    <!--Card-->\r\n");
      out.write("    <div class=\"card mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <!--Card image-->\r\n");
      out.write("        <div class=\"view overlay\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"images/img1.jpg\" width=100% height=\"100%\" alt=\"Card image cap\">\r\n");
      out.write("            <a href=\"#!\">\r\n");
      out.write("                <div class=\"mask rgba-white-slight\"></div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--Card image-->\r\n");
      out.write("\r\n");
      out.write("        <!--Card content-->\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("            <!--Title-->\r\n");
      out.write("            <h4 class=\"card-title\">C Programming</h4>\r\n");
      out.write("\r\n");
      out.write("            <!--Text-->\r\n");
      out.write("            \r\n");
      out.write("      \r\n");
      out.write("            <p class=\"card-text\" style=\"text-align: justify;\">C is a general-purpose, imperative computer programming language, supporting structured programming, \r\n");
      out.write("            lexical variable scope and recursion, while a static type system prevents many unintended operations.</p>\r\n");
      out.write("\r\n");
      out.write("            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-light-blue btn-md\">Read more</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--Card content-->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--Card-->\r\n");
      out.write("\r\n");
      out.write("    <!--Card-->\r\n");
      out.write("    <div class=\"card mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <!--Card image-->\r\n");
      out.write("        <div class=\"view overlay\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"images/img2.jpg\" width=100% height=\"100%\" alt=\"Card image cap\">\r\n");
      out.write("            <a href=\"#!\">\r\n");
      out.write("                <div class=\"mask rgba-white-slight\"></div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--Card image-->\r\n");
      out.write("\r\n");
      out.write("        <!--Card content-->\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <!--Title-->\r\n");
      out.write("            <h4 class=\"card-title\">C++ Programming</h4>\r\n");
      out.write("\r\n");
      out.write("            <!--Text-->\r\n");
      out.write("            <p class=\"card-text\" style=\"text-align: justify;\">C++ (pronounced \"see plus plus\") is a computer programming language based on C. \r\n");
      out.write("            It was created for writing programs for many different purposes.The C++ programming language was developed by Bjarne Stroustrup at Bell Labs in the 1980s</p>\r\n");
      out.write("\r\n");
      out.write("            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-light-blue btn-md\">Read more</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--Card content-->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--Card-->\r\n");
      out.write("\r\n");
      out.write("    <!--Card-->\r\n");
      out.write("    <div class=\"card mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <!--Card image-->\r\n");
      out.write("        <div class=\"view overlay\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"images/img1.jpg\" width=100% height=\"100%\" alt=\"Card image cap\">\r\n");
      out.write("            <a href=\"#!\">\r\n");
      out.write("                <div class=\"mask rgba-white-slight\"></div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--Card image-->\r\n");
      out.write("\r\n");
      out.write("        <!--Card content-->\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <!--Title-->\r\n");
      out.write("            <h4 class=\"card-title\">JavaProgramming</h4>\r\n");
      out.write("\r\n");
      out.write("            <!--Text-->\r\n");
      out.write("            <p class=\"card-text\" style=\"text-align: justify;\">Java was originally developed by James Gosling at Sun Microsystems \r\n");
      out.write("            (which has since been acquired by Oracle Corporation) and released in 1995 as a core component of Sun Microsystems' Java platform.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-light-blue btn-md\">Read more</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--Card content-->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--Card-->\r\n");
      out.write("  <!--Card-->\r\n");
      out.write("      <div class=\"card mb-4\">\r\n");
      out.write("\r\n");
      out.write("        <!--Card image-->\r\n");
      out.write("        <div class=\"view overlay\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"images/img5.png\" width=57% height=\"57%\" alt=\"Card image cap\">\r\n");
      out.write("            <a href=\"https://www.youtube.com/channel/UCARc3v6818KY-BfmOc2efUQ?view_as=subscriber\">\r\n");
      out.write("                <div class=\"mask rgba-white-slight\"></div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--Card image-->\r\n");
      out.write("\r\n");
      out.write("        <!--Card content-->\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <!--Title-->\r\n");
      out.write("            <h4 class=\"card-title\">@FollowFaceBookPage</h4>\r\n");
      out.write("\r\n");
      out.write("            <!--Text-->\r\n");
      out.write("<div class=\"fb-page\" data-href=\"https://www.facebook.com/jprogrammingin-1682438655409294/\" data-tabs=\"timeline\" data-height=\"90\" data-small-header=\"false\" data-adapt-container-width=\"true\" data-hide-cover=\"false\" data-show-facepile=\"true\"><blockquote cite=\"https://www.facebook.com/jprogrammingin-1682438655409294/\" class=\"fb-xfbml-parse-ignore\">\r\n");
      out.write("<a href=\"https://www.facebook.com/jprogrammingin-1682438655409294/\">jprogramming.in</a></blockquote></div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-light-blue btn-md\">Read more</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--Card content-->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--Card-->\r\n");
      out.write("</div>\r\n");
      out.write("<!--Card group-->\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    <div class=\"thumbnail\">\r\n");
      out.write("        <hr>\r\n");
      out.write("        <center><h5>News Update</h5></center>\r\n");
      out.write("        \r\n");
      out.write("         <marquee id='scroll_news' ><div onMouseOver=\"document.getElementById('scroll_news').stop();\" onMouseOut=\"document.getElementById('scroll_news').start();\"><img class=\"img-circle\" src=\"images/new.jpg\" width=\"30px\" height=\"30px\"/><a href=\"https://www.youtube.com/channel/UCARc3v6818KY-BfmOc2efUQ?view_as=subscriber\" style=\"font-family:Book Antiqua;color:#ff0001\">GetSubscribeNewVideos@JHCProgramming</a></div></marquee>\r\n");
      out.write("\r\n");
      out.write(" <marquee id='scroll_news' ><div onMouseOver=\"document.getElementById('scroll_news').stop();\" onMouseOut=\"document.getElementById('scroll_news').start();\"><img class=\"img-circle\" src=\"images/new.jpg\" width=\"30px\" height=\"30px\"/><a href=\"https://www.youtube.com/playlist?list=PLExUa3EURkZVniQIyUuok-svoBpRFquAo\" style=\"font-family:Book Antiqua;color:#ff0001\">C Tutorial Tamil Videos</a></div></marquee>\r\n");
      out.write("        <hr/>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
