/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2018-04-03 11:01:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class javavideos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Tutorials-JavaVideos</title>\n");
      out.write("      <!-- Font Awesome -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write(" \n");
      out.write("    <!-- Material Design Bootstrap -->\n");
      out.write("    <link href=\"css/mdb.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Your custom styles (optional) -->\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\n");
      out.write(" \n");
      out.write("    \n");
      out.write("       \n");
      out.write("     <!-- SCRIPTS -->\n");
      out.write("    <!-- JQuery -->\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-3.2.1.min.js\"></script>\n");
      out.write("    <!-- Bootstrap tooltips -->\n");
      out.write("    <script type=\"text/javascript\" src=\"js/popper.min.js\"></script>\n");
      out.write("    <!-- Bootstrap core JavaScript -->\n");
      out.write("    <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\n");
      out.write("    <!-- MDB core JavaScript -->\n");
      out.write("    <script type=\"text/javascript\" src=\"js/mdb.min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t$(\"#myModal\").modal('show');\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("   \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("       \n");
      out.write("       <!-- embedcode start -->\n");
      out.write("       \n");
      out.write("<!--Grid row-->\n");
      out.write("<div class=\"row mb-5\">\n");
      out.write("\n");
      out.write("    <!--Grid column-->\n");
      out.write("    <div class=\"col-lg-4 col-md-12\">\n");
      out.write("\n");
      out.write("        <p class=\"h5 mb-4\"><code>Part-1 SimpleJavaProgram-Tamil</code></p>\n");
      out.write("\n");
      out.write("        <div class=\"embed-responsive embed-responsive-16by9 z-depth-1\">\n");
      out.write("            <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/WKx6zlJ8YOs\" style=\"height: 101%\" allowfullscreen></iframe>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!--Grid column-->\n");
      out.write("\n");
      out.write("    <!--Grid column-->\n");
      out.write("    <div class=\"col-lg-4 col-md-6\">\n");
      out.write("\n");
      out.write("        <p class=\"h5 mb-4\"><code>Part-2 Arguments-passing in JAVA-Tamil</code></p>\n");
      out.write("\n");
      out.write("        <div class=\"embed-responsive embed-responsive-16by9 z-depth-1-half\">\n");
      out.write("            <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/-VFVZ6iGmkI\" style=\"height: 101%\" allowfullscreen></iframe>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!--Grid column-->\n");
      out.write("\n");
      out.write("    <!--Grid column-->\n");
      out.write("    <div class=\"col-lg-4 col-md-6\">\n");
      out.write("\n");
      out.write("        <p class=\"h5 mb-4\"><code>Variables in Java</code></p>\n");
      out.write("\n");
      out.write("        <div class=\"embed-responsive embed-responsive-16by9 z-depth-2\">\n");
      out.write("            <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/MkRHtd4Us2k\" style=\"height: 101%\" allowfullscreen></iframe>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!--Grid column-->\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!--Grid row-->\n");
      out.write("\n");
      out.write("<!--Grid row-->\n");
      out.write("<div class=\"row mb-5\">\n");
      out.write("\n");
      out.write("    <!--Grid column-->\n");
      out.write("    <div class=\"col-lg-4 col-md-12\">\n");
      out.write("\n");
      out.write("        <p class=\"h5 mb-4\"><code>Operators in Java Basics</code></p>\n");
      out.write("\n");
      out.write("        <div class=\"embed-responsive embed-responsive-16by9 z-depth-3\">\n");
      out.write("            <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/Vk6NTiX1Mz0\" allowfullscreen></iframe>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!--Grid column-->\n");
      out.write("\n");
      out.write("<!--     Grid column -->\n");
      out.write("<!--     <div class=\"col-lg-4 col-md-6\"> -->\n");
      out.write("\n");
      out.write("<!--         <p class=\"h5 mb-4\"><code>.z-depth-4</code></p> -->\n");
      out.write("\n");
      out.write("<!--         <div class=\"embed-responsive embed-responsive-16by9 z-depth-4\"> -->\n");
      out.write("<!--             <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/fa3Iczgh8Ok\" allowfullscreen></iframe> -->\n");
      out.write("<!--         </div> -->\n");
      out.write("\n");
      out.write("<!--     </div> -->\n");
      out.write("<!--     Grid column -->\n");
      out.write("\n");
      out.write("    <!--Grid column-->\n");
      out.write("    <div class=\"col-lg-4 col-md-6\">\n");
      out.write("\n");
      out.write("        <p class=\"h5 mb-4\"><code>BasicJavaProgram</code></p>\n");
      out.write("\n");
      out.write("        <div class=\"embed-responsive embed-responsive-16by9 z-depth-5\">\n");
      out.write("            <iframe class=\"embed-responsive-item\" src=\"https://www.youtube.com/embed/oKx3afeaDRM\" allowfullscreen></iframe>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!--Grid column-->\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!--Grid row-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                \n");
      out.write("       <!-- embedcode end -->\n");
      out.write("<div id=\"myModal\" class=\"modal fade\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n");
      out.write("                <h4 class=\"modal-title\">Subscribe our JHCPROGRAMMING</h4>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("\t\t\t\t<p>Subscribe to our Youtube Channel</p>\n");
      out.write("                <p>Click Subscribe Button</p>\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\"><a href=\"https://www.youtube.com/channel/UCARc3v6818KY-BfmOc2efUQ?view_as=subscriber\">Subscribe</a></button>\n");
      out.write("               \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("                \n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
