/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-08-21 06:15:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Form Validation:Demo Preview</title>\r\n");
      out.write("<meta content=\"noindex, nofollow\" name=\"robots\">\r\n");
      out.write("<link href=\"formvalid.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"formvalid.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"form\">\r\n");
      out.write("<p id=\"head\"></p>\r\n");
      out.write("<!-- This segment displays the validation rule -->\r\n");
      out.write("<h2>JavaScript Form Validation</h2>\r\n");
      out.write("<!-- Form starts from here -->\r\n");
      out.write("<form onsubmit='return formValidation()'>\r\n");
      out.write("<label>Full Name:</label>\r\n");
      out.write("<input id='firstname' type='text'>\r\n");
      out.write("<p id=\"p1\"></p>\r\n");
      out.write("<!-- This segment displays the validation rule for name -->\r\n");
      out.write("<label>Username(6-8 characters):</label>\r\n");
      out.write("<input id='username' type='text'>\r\n");
      out.write("<p id=\"p2\"></p>\r\n");
      out.write("<!-- This segment displays the validation rule for user name -->\r\n");
      out.write("<label>Email:</label>\r\n");
      out.write("<input id='email' type='text'>\r\n");
      out.write("<p id=\"p3\"></p>\r\n");
      out.write("<!-- This segment displays the validation rule for email -->\r\n");
      out.write("<label>State:</label>\r\n");
      out.write("<select id='state'>\r\n");
      out.write("<option>\r\n");
      out.write("Please Choose\r\n");
      out.write("</option>\r\n");
      out.write("<option>\r\n");
      out.write("America\r\n");
      out.write("</option>\r\n");
      out.write("<option>\r\n");
      out.write("Australia\r\n");
      out.write("</option>\r\n");
      out.write("<option>\r\n");
      out.write("Sweden\r\n");
      out.write("</option>\r\n");
      out.write("<option>\r\n");
      out.write("Africa\r\n");
      out.write("</option>\r\n");
      out.write("</select>\r\n");
      out.write("<p id=\"p4\"></p>\r\n");
      out.write("<!-- This segment displays the validation rule for selection -->\r\n");
      out.write("<label>Address:</label>\r\n");
      out.write("<input id='addr' type='text'>\r\n");
      out.write("<p id=\"p5\"></p>\r\n");
      out.write("<!-- This segment displays the validation rule for address -->\r\n");
      out.write("<label>Zip Code:</label>\r\n");
      out.write("<input id='zip' type='text'>\r\n");
      out.write("<p id=\"p6\"></p>\r\n");
      out.write("<!-- This segment displays the validation rule for zip -->\r\n");
      out.write("<input id=\"submit\" type='submit' value='Check Form'>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
